apiVersion: v1
kind: Service
metadata:
  annotations:
    compose.cmd: docker-compose
    compose.version: 1.31.2
  labels:
    io.compose.service: calculator
  name: calculator
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000  
  selector:
    io.compose.service: calculator
status:
  loadBalancer: {}
