apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-watch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-watch  # Matches the labels in the template
  template:
    metadata:
      labels:
        app: docker-watch
    spec:
      containers:
        - name: docker-watch-container
          image: docker-watch:latest
          imagePullPolicy: IfNotPresent  # Set the image pull policy here
