apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-watch-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-watch
  template:
    metadata:
      labels:
        app: docker-watch
    spec:
      containers:
        - name: docker-watch-container
          image: docker-watch:latest
          ports:
            - containerPort: 8080
