apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-watch-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-watch
  template:
    metadata:
      labels:
        app: docker-watch
    spec:
      containers:
        - name: docker-watch-container
          image: sonawaneyogeshb/docker-watch:latest
          imagePullPolicy: IfNotPresent  # Set the image pull policy here
          ports:
            - containerPort: 8080
